### ISSUE TITLE
Webpack 5 Adoption

### ISSUE THREAD

**Issue by gabrieldejesus** [jpedroschmitz/typescript-nextjs-starter#148]
# ✨ Webpack 5 Adoption

Hey @jpedroschmitz  what do you think about considering the adoption of ``Webpack 5`` in your template?

Just create a ``next.config.js`` file and adding the flag to it:

```js
module.exports = {
  future: {
    webpack5: true,
  },
}
```

References:
- https://nextjs.org/docs/messages/webpack5

**Comment by jpedroschmitz** [comment]
Hey, @gabrieldejesus, that would be super nice!

I'd happily accept a PR for this =D

**Comment by gabrieldejesus** [comment]
Well, I'm glad to know that.
Please @jpedroschmitz  check this pul request https://github.com/jpedroschmitz/typescript-nextjs-starter/pull/149
