### ISSUE TITLE
Remove npm install from README

### ISSUE THREAD

**Issue by Jhappy77** [jpedroschmitz/typescript-nextjs-starter#258]
The readme recommends using `npm install` after cloning the repository, and adds that you can use `yarn install` as an alternative.  I think that it should only recommend using `yarn install`.

Reasons:
- The repo comes with a premade yarnlock and no package-lock
- The CI checks use yarn. If a user uses npm instead of yarn to install their packages, and continues to use npm, these checks will fail because yarn will realize the yarnlock is outdated. 

I think it would be best to strongly encourage people to use yarn with this setup since that's what everything is written with. This will avoid confusing newcomers - and if converting to npm easily remains important, perhaps a conversion process could be described in the README.

**Comment by jpedroschmitz** [comment]
Hey, @Jhappy77, that makes sense! I'll open a PR to remove it!

Thanks a lot =D
