### ISSUE TITLE
Add .env to .gitignore

### ISSUE THREAD

**Issue by davevanhoorn** [jpedroschmitz/typescript-nextjs-starter#367]
I love this starter, but now made the (dumb) mistake of commiting a .env file to my repo for the second time. Is there a reason you haven't added a regular `.env` to `.gitignore`?

PR: https://github.com/jpedroschmitz/typescript-nextjs-starter/pull/368

**Comment by jpedroschmitz** [comment]
I was using the same `.gitignore` created by next.js, but we can add `.env` to `.gitignore`.

**Comment by jpedroschmitz** [comment]
PR merged! Thanks a lot for opening it ❤️
