### ISSUE TITLE
Bump node version to a newer lts?

### ISSUE THREAD

**Issue by Kavinjsir** [jpedroschmitz/typescript-nextjs-starter#490]
Current version in `.nvmrc` is `v12.22.0`.  Would it be better to set a newer lts one such as `v16.16.0`?

I'm not sure if it is common, my case is:
When using `fnm`, it will detect `.nvmrc` and keep suggesting me to switch to the version specified in it.

Considering on `node14` or `node16` to be more general now, an update of `.nvmrc` might can reduce bothering many users.

**Comment by jpedroschmitz** [comment]
Hey @Kavinjsir, the Node.js version we have defined in `.nvmrc` is the minimum required by Next.js: https://nextjs.org/docs/getting-started#system-requirements

I think it would be better to use Node 16 since it's the LTS now, and Node.js 12 is depreciated.

Do you want to open a PR for it?

**Comment by Kavinjsir** [comment]
> Hey @Kavinjsir, the Node.js version we have defined in `.nvmrc` is the minimum required by Next.js: https://nextjs.org/docs/getting-started#system-requirements
> 
> I think it would be better to use Node 16 since it's the LTS now, and Node.js 12 is depreciated.
> 
> Do you want to open a PR for it?

Sure thing.
Have initialized a PR at:
https://github.com/jpedroschmitz/typescript-nextjs-starter/pull/494

I'm very new to the project so let me know if I'm missing something or any suggestions. Thx!

**Comment by Kavinjsir** [comment]
I might close this issue since we have `v16` now.

**Comment by jpedroschmitz** [comment]
Thanks, @Kavinjsir!
