### ISSUE TITLE
Cannot Run Dev server

### ISSUE THREAD

**Issue by chaudharykiran** [jpedroschmitz/typescript-nextjs-starter#685]
Module not found: Can't resolve 'base64-js'

I cloned this repo using 

>npx create-next-app ts-next -e https://github.com/jpedroschmitz/typescript-nextjs-starter
>yarn
>yarn dev

I am getting Module not found error when trying to open page in localhost. 

My Node version is

v18.16.0

Anyhint how to solve this error?

**Comment by jpedroschmitz** [comment]
This template uses pnpm as a package manager. Please take a look at this section on how to switch to Yarn: https://github.com/jpedroschmitz/typescript-nextjs-starter#switch-to-yarnnpm
