### ISSUE TITLE
Deploying to firebase

### ISSUE THREAD

**Issue by AliSiddique** [jpedroschmitz/typescript-nextjs-starter#707]
I have added the .next as the output directory in firebase.json but the output is not found?

**Comment by jpedroschmitz** [comment]
Hey @AliSiddique! I have never deployed a Next.js app to Firebase, so I cannot help you.

Have you tried following the official Firebase guide on deploying it?

https://firebase.google.com/docs/hosting/frameworks/nextjs

**Comment by AliSiddique** [comment]
I have read about next.js and firebase and it seems the support is not that good.  I am just going to deploy using vercel.  Thank you anyway.
