### ISSUE TITLE
Add testing setup (e.g. jest, testing-library)

### ISSUE THREAD

**Issue by mwehnert** [jpedroschmitz/typescript-nextjs-starter#99]
In addition to eslint, prettier and typescript setup on a blank nextjs project, preparing testing especially with the git hooks and script etc. would be great

**Comment by jpedroschmitz** [comment]
Hey @mwehnert, I think it would be great. My concern is to have so many things installed and ready to go on the starter that it will become hard to use. So far it's simple to use it. What do you think?

**Comment by mwehnert** [comment]
I see what you mean. But I think the testing stuff could be a great enhancement. And because everything would be devdependencies I see no problem. If you do testing in the nextjs app is still completely optional, but if you like to (for example for some more complex helper functions) everything is there and ready to use. I like the idea 💁‍♂️

**Comment by jpedroschmitz** [comment]
Yes, just like create-react-app that has tests configured by default, but still optional to use.

I'll add to my tasks and create a PR as soon as possible 💜

**Comment by saiyamjain143** [comment]
@jpedroschmitz Any update on adding testing dependencies?

**Comment by jpedroschmitz** [comment]
Hey, not yet, unfortunately.

I was thinking about this, and maybe we could have a separate branch for tests. Same setup, but with tests. WDYT?

I'm still not sure if the best solution is to include everything in the main branch. Most projects won't need this since just a few of them end up writing tests, but I may be wrong about this.

Let me know what y'all think.

**Comment by caiotracera** [comment]
Hey, @jpedroschmitz.
I don't know if you're still thinking about this, but I'd like to add my contribution: the idea of adding the tests in a separate branch is great. That way, I can feel like Hannah Montana and have the best of both worlds: a simple template, for small projects, and a robust template for larger projects.


<img src="https://i.giphy.com/media/fDqGThpuG6vS/giphy.webp"  />

And if this idea goes ahead, I think it's also worth considering adding Storybook. It is even less necessary than the tests, but a great addition that makes all the difference in my opinion. WDYT?

**Comment by jpedroschmitz** [comment]
I like the idea of keeping tests in a separate branch, but the main problem of this is maintaining both branches. Anyways, I think we should try. 

Does anyone want to open a PR for adding tests? I don't have time for that right now.

**Comment by caiotracera** [comment]
@jpedroschmitz 
I've created a fork and added Jest on a new branch called `with-tests`, but I'm not able to create the branch in this repository. When I create the PR from my fork to this repo, I can only compare with the main branch. Can you create the branch, so I can create the PR?

My fork with the new branch: https://github.com/caiotracera/typescript-nextjs-starter/tree/with-tests

**Comment by jpedroschmitz** [comment]
Thanks a lot for your work on this, @caiotracera!

I decided not to add tests to the project. There are many testing options these days, and I don't want to be opinionated on this. It will go against the template principles. I'll close this issue, but if anyone wants to add tests, they can have your repo as a base.
